// Code generated by counterfeiter. DO NOT EDIT.
package dependenciesfakes

import (
	"context"
	"sync"

	"github.com/hugocorbucci/onde-2a-dose-backend/internal/dependencies"
	"github.com/hugocorbucci/onde-2a-dose-backend/internal/dependencies/prefeitura"
)

type FakeDeOlhoNaFila struct {
	FetchStub        func(context.Context) ([]*prefeitura.DeOlhoNaFilaUnit, error)
	fetchMutex       sync.RWMutex
	fetchArgsForCall []struct {
		arg1 context.Context
	}
	fetchReturns struct {
		result1 []*prefeitura.DeOlhoNaFilaUnit
		result2 error
	}
	fetchReturnsOnCall map[int]struct {
		result1 []*prefeitura.DeOlhoNaFilaUnit
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeDeOlhoNaFila) Fetch(arg1 context.Context) ([]*prefeitura.DeOlhoNaFilaUnit, error) {
	fake.fetchMutex.Lock()
	ret, specificReturn := fake.fetchReturnsOnCall[len(fake.fetchArgsForCall)]
	fake.fetchArgsForCall = append(fake.fetchArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.FetchStub
	fakeReturns := fake.fetchReturns
	fake.recordInvocation("Fetch", []interface{}{arg1})
	fake.fetchMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeDeOlhoNaFila) FetchCallCount() int {
	fake.fetchMutex.RLock()
	defer fake.fetchMutex.RUnlock()
	return len(fake.fetchArgsForCall)
}

func (fake *FakeDeOlhoNaFila) FetchCalls(stub func(context.Context) ([]*prefeitura.DeOlhoNaFilaUnit, error)) {
	fake.fetchMutex.Lock()
	defer fake.fetchMutex.Unlock()
	fake.FetchStub = stub
}

func (fake *FakeDeOlhoNaFila) FetchArgsForCall(i int) context.Context {
	fake.fetchMutex.RLock()
	defer fake.fetchMutex.RUnlock()
	argsForCall := fake.fetchArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeDeOlhoNaFila) FetchReturns(result1 []*prefeitura.DeOlhoNaFilaUnit, result2 error) {
	fake.fetchMutex.Lock()
	defer fake.fetchMutex.Unlock()
	fake.FetchStub = nil
	fake.fetchReturns = struct {
		result1 []*prefeitura.DeOlhoNaFilaUnit
		result2 error
	}{result1, result2}
}

func (fake *FakeDeOlhoNaFila) FetchReturnsOnCall(i int, result1 []*prefeitura.DeOlhoNaFilaUnit, result2 error) {
	fake.fetchMutex.Lock()
	defer fake.fetchMutex.Unlock()
	fake.FetchStub = nil
	if fake.fetchReturnsOnCall == nil {
		fake.fetchReturnsOnCall = make(map[int]struct {
			result1 []*prefeitura.DeOlhoNaFilaUnit
			result2 error
		})
	}
	fake.fetchReturnsOnCall[i] = struct {
		result1 []*prefeitura.DeOlhoNaFilaUnit
		result2 error
	}{result1, result2}
}

func (fake *FakeDeOlhoNaFila) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.fetchMutex.RLock()
	defer fake.fetchMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeDeOlhoNaFila) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ dependencies.DeOlhoNaFila = new(FakeDeOlhoNaFila)
